/* DO NOT EDIT! This file was automatically generated by config */

#ifndef LUA_DEFAULT_PATH
#define LUA_DEFAULT_PATH "/site/lualib/?.ljbc;/site/lualib/?/init.ljbc;/lualib/?.ljbc;/lualib/?/init.ljbc;/site/lualib/?.lua;/site/lualib/?/init.lua;/lualib/?.lua;/lualib/?/init.lua"
#endif

#ifndef LUA_DEFAULT_CPATH
#define LUA_DEFAULT_CPATH "/site/lualib/?.so;/lualib/?.so"
#endif

